name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        git submodule init && git submodule update
        mkdir build
        cd build
        cmake ..
    - name: make
      run: cd build && make
